Revert "added missing space"
This reverts commit e271b7f40ddb7a30e88b9fcbdcae22ceb031bc73.

diff --git a/functions/fn_install_config b/functions/fn_install_config
--- a/functions/fn_install_config
+++ b/functions/fn_install_config
@@ -174,23 +174,22 @@ echo ""
 echo "Creating Configs"
 echo "================================="
 sleep 1
-if [ -z ${servercfgdir+x} ];
-	if [ ! -d "${servercfgdir}" ]; then
-		echo -e "creating ${servercfgdir} dir...\c"
-		mkdir -pv "${servercfgdir}"
-		if [[ $? == 0 ]]; then
-			echo -e  "OK"
-		else
-			echo -e  "FAIL"
-		fi
+if [ ! -d "${servercfgdir}" ]; then
+	echo -e "creating ${servercfgdir} dir...\c"
+	mkdir -pv "${servercfgdir}"
+	if [[ $? == 0 ]]; then
+		echo -e  "OK"
+	else
+		echo -e  "FAIL"
 	fi
 fi
+
 if [ "${gamename}" == "ARMA 3" ]; then
 	cd "${systemdir}"
 else
 	cd "${servercfgdir}"
 fi
-
+	#statements
 if [ "${gamename}" == "7 Days To Die" ]; then
 	fn_unity3dconfig
 elif [ "${gamename}" == "ARK: Survivial Evolved" ]; then
