Migrated to new split functions system
All scripts now have the new split functions system in-place.

Some functions now have there own file rather than being in the main
script file.
If the main script requires the file is will automatically download it
in the the functions dir for use.

Only a few functions currently do this. However if a change is made to a
function it will be migrated. In the long term this will reduce the need
for me to copy the same code over 20 times and drastically reduce the
time it takes me to make changes.

diff --git a/CounterStrikeGlobalOffensive/csgoserver b/CounterStrikeGlobalOffensive/csgoserver
--- a/CounterStrikeGlobalOffensive/csgoserver
+++ b/CounterStrikeGlobalOffensive/csgoserver
@@ -3,7 +3,7 @@
 # Server Management Script
 # Author: Daniel Gibbs
 # Website: http://danielgibbs.co.uk
-# Version: 061014
+# Version: 121114
 
 #### Variables ####
 
@@ -217,46 +217,11 @@ fi
 }
 
 fn_debugserver(){
-fn_rootcheck
-fn_syscheck
-fn_autoip
-fn_distro
-fn_uptime
-fn_load
-fn_parms
-echo ""
-echo "${gamename} Debug"
-echo "============================"
-echo ""
-echo -e "Distro: ${os}"
-echo -e "Arch: ${arch}"
-echo -e "Kernel: ${kernel}"
-echo -e "Hostname: $HOSTNAME"
-echo ""
-echo "Start parameters:"
-echo ${parms}
-echo ""
-echo -e "Use for identifying server issues only!"
-echo -e "Press CTRL+c to drop out of debug mode"
-echo -e "\e[0;31mWARNING!\e[0;39m If ${servicename} is already running it will be stopped"
-echo ""
-while true; do
-	read -p "Continue? [y/N]" yn
-	case $yn in
-	[Yy]* ) break;;
-	[Nn]* ) echo Exiting; return 1;;
-	* ) echo "Please answer yes or no.";;
-esac
-done
-fn_stopserver
-fn_printdots "Starting debug mode ${servicename}: ${servername}"
-sleep 1
-fn_printok "Starting debug mode ${servicename}: ${servername}"
-sleep 1
-fn_scriptlog "Started debug mode ${servername}"
-echo -en "\n"
-cd "${executabledir}"
-${executable} ${parms} -debug
+if [ ! -f functions/fn_debugserver ]; then
+	functionfile="fn_debugserver"
+	fn_fninstall
+fi
+source functions/fn_debugserver
 }
 
 fn_console(){
@@ -662,39 +627,29 @@ echo -en "\n"
 }
 
 fn_details(){
-fn_autoip
-servername=$(grep -s hostname "${servercfgfullpath}"|sed 's/hostname //g'|sed 's/"//g')
-rcon=$(grep -s rcon_password "${servercfgfullpath}"|sed 's/rcon_password //g'|sed 's/"//g')
-pid=$(tmux list-sessions 2>&1|awk '{print $1}'|grep -E "^${servicename}:"|wc -l)
-echo ""
-echo "${gamename} Server Details"
-echo "============================"
-echo "Server name: ${servername}"
-echo "Server IP: ${ip}:${port}"
-echo "RCON password: ${rcon}"
-echo "Config file: ${servercfgfullpath}"
-echo ""
-echo "${servername} Ports"
-echo "============================"
-echo "Ports the server is currently using."
-echo ""
-echo "DIRECTION	DESCRIPTION		PORT"
-echo "INBOUND		Game/RCON port		${port}"
-if [ ! -z ${sourcetvport} ]; then
-	echo "INBOUND		SourceTV port		${sourcetvport}"
+if [ ! -f functions/fn_details ]; then
+	functionfile="fn_details"
+	fn_fninstall
 fi
-echo "OUTBOUND	Client port		${clientport}"
-echo ""
-echo "You can change ports by editing the"
-echo "start parameters in ${selfname}."
-echo ""
-if [ "${pid}" == "0" ]; then
-	echo -e "Status:\e[0;31m OFFLINE\e[0;39m"
-else
-	echo -e "Status:\e[0;32m ONLINE\e[0;39m"
+source functions/fn_details
+}
+
+fn_fninstall(){
+cd ${rootdir}	
+if [ ! -d "functions" ]; then
+	mkdir functions
 fi
+echo ""
+echo "loading ${functionfile}..."
+cd functions
+wget -nv -N https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/functions/${functionfile}
+chmod +x ${functionfile}
+cd ${rootdir}
+sleep 1
 echo ""
 }
+
+# Game Specific Functions
 
 fn_csgoappidfix(){
 if [ ! -f "${filesdir}/steam_appid.txt" ]; then
@@ -704,6 +659,60 @@ if [ ! -f "${filesdir}/steam_appid.txt" ]; then
 	sleep 1
 	echo -en "\n"
 	echo -n "730" >> ${filesdir}/steam_appid.txt
+fi
+}
+
+# Fixes the following error
+# Error parsing BotProfile.db - unknown attribute 'Rank"
+fn_botprofilefix(){
+if ! grep -q "//Rank" "${systemdir}/botprofile.db" ; then
+	echo "botprofile.db fix removes the following error from appearing on the console:"
+	echo "	Error parsing BotProfile.db - unknown attribute 'Rank"
+	sleep 1
+	fn_printdots "Applying botprofile.db fix."
+	sleep 1
+	fn_printinfo "Applying botprofile.db fix."
+	sleep 1
+	sed -i 's/\tRank/\t\/\/Rank/g' "${systemdir}/botprofile.db"
+	echo -en "\n"
+	echo ""
+fi
+}
+
+# Fixes errors simular to the following
+# Unknown command "cl_bobamt_vert"
+fn_valvetcfix(){
+if ! grep -q "//exec default" "${servercfgdir}/valve.rc" || ! grep -q "//exec joystick" "${servercfgdir}/valve.rc"; then
+	echo "valve.rc fix removes the following error from appearing on the console:"
+	echo "	Unknown command \"cl_bobamt_vert\""
+	sleep 1
+	fn_printdots "Applying valve.rc fix."
+	sleep 1
+	fn_printinfo "Applying valve.rc fix."
+	sleep 1
+	sed -i 's/exec default.cfg/\/\/exec default.cfg/g' "${servercfgdir}/valve.rc"
+	sed -i 's/exec joystick.cfg/\/\/exec joystick.cfg/g' "${servercfgdir}/valve.rc"
+	echo -en "\n"
+	echo ""
+fi
+}
+
+# Fixes errors simular to the following
+# http://forums.steampowered.com/forums/showthread.php?t=3170366
+fn_workshopmapfix(){
+if [ -f "${systemdir}/subscribed_collection_ids.txt" ]||[ -f "${systemdir}/subscribed_file_ids.txt" ]||[ -f "${systemdir}/ugc_collection_cache.txt" ]; then
+	echo "workshopmapfix fixes the following error:"
+	echo "	http://forums.steampowered.com/forums/showthread.php?t=3170366"
+	sleep 1
+	fn_printdots "Applying workshopmap fix."
+	sleep 1
+	fn_printinfo "Applying workshopmap fix."
+	sleep 1
+	rm -f "${systemdir}/subscribed_collection_ids.txt"
+	rm -f "${systemdir}/subscribed_file_ids.txt"
+	rm -f "${systemdir}/ugc_collection_cache.txt"
+	echo -en "\n"
+	echo ""
 fi
 }
 
@@ -764,14 +773,11 @@ echo ""
 }
 
 fn_steamfix(){
-echo "Applying steamclient.so fix"
-echo "================================="
-sleep 1
-mkdir -pv "${HOME}/.steam"
-mkdir -pv "${HOME}/.steam/sdk32"
-cp -v "${rootdir}/steamcmd/linux32/steamclient.so" "${HOME}/.steam/sdk32/steamclient.so"
-sleep 1
-echo ""
+if [ ! -f functions/fn_steamfix ]; then
+	functionfile="fn_steamfix"
+	fn_fninstall
+fi	
+source functions/fn_steamfix
 }
 
 fn_loginstall(){
@@ -852,45 +858,50 @@ fn_loginstall
 fn_getquery
 echo "Configuring ${gamename} Server"
 echo "================================="
-	sleep 1
-	read -p "Enter server name: " servername
-	read -p "Enter rcon password: " rconpass
-	sleep 1
-	echo "Creating server.cfg."
-	touch "${defaultcfg}"
-	echo "exec ${servicename}.cfg" > "${defaultcfg}"
-	sleep 1
-	echo "Creating ${servicename}.cfg config file."
-	touch "${servercfgfullpath}"
-	{
-		echo -e "// server name"
-		echo -e "hostname \"${servername}\""
-		echo -e ""
-		echo -e "// rcon passsword"
-		echo -e "rcon_password \"${rconpass}\""
-		echo -e ""
-		echo -e "// Server password"
-		echo -e "sv_password \"\""
-		echo -e ""
-		echo -e "// server logging"
-		echo -e "log on"
-		echo -e "sv_logbans 1"
-		echo -e "sv_logecho 1"
-		echo -e "sv_logfile 1"
-		echo -e "sv_log_onefile 0"
-	}|tee "${servercfgfullpath}" > /dev/null 2>&1
-	sleep 1
-	echo ""
-	fn_header
-	sleep 1
-	fn_details
-	sleep 1
-	echo "================================="
-	echo "Install Complete!"
-	echo ""
-	echo "To start server type:"
-	echo "${selfname} start"
-	echo ""
+sleep 1
+read -p "Enter server name: " servername
+read -p "Enter rcon password: " rconpass
+sleep 1
+echo "Creating server.cfg."
+touch "${defaultcfg}"
+echo "exec ${servicename}.cfg" > "${defaultcfg}"
+sleep 1
+echo "Creating ${servicename}.cfg config file."
+touch "${servercfgfullpath}"
+{
+	echo -e "// Server Name"
+	echo -e "hostname \"${servername}\""
+	echo -e ""
+	echo -e "// RCON Password"
+	echo -e "rcon_password \"${rconpass}\""
+	echo -e ""
+	echo -e "// Server Password"
+	echo -e "sv_password \"\""
+	echo -e ""
+	echo -e "// Server Logging"
+	echo -e "log on"
+	echo -e "sv_logbans 1"
+	echo -e "sv_logecho 1"
+	echo -e "sv_logfile 1"
+	echo -e "sv_log_onefile 0"
+}|tee "${servercfgfullpath}" > /dev/null 2>&1
+sleep 1
+echo ""
+echo "Applying ${gamename} Fixes"
+echo "================================="
+fn_botprofilefix
+fn_valvetcfix
+fn_workshopmapfix
+fn_header
+sleep 1
+fn_details
+sleep 1
+echo "================================="
+echo "Install Complete!"
+echo ""
+echo "To start server type:"
+echo "${selfname} start"
+echo ""
 }
 
 case "$1" in
